
import { AntibioticMatrix } from './types';

export const antibioticMatrix: AntibioticMatrix = {
  // Cocos Gram Positivos
  'Staphylococcus aureus': {
    // Beta-lactâmicos
    'Penicilina G': 'resistant',
    'Penicilina V': 'resistant',
    'Ampicilina': 'resistant',
    'Amoxicilina': 'resistant',
    'Amoxicilina-Clavulanato': 'variable',
    'Ampicilina-Sulbactam': 'variable',
    'Oxacilina': 'variable',
    'Cloxacilina': 'variable',
    'Cefazolina': 'variable',
    'Cefalexina': 'variable',
    'Cefuroxima': 'variable',
    'Cefoxitina': 'variable',
    'Ceftriaxone': 'variable',
    'Cefotaxima': 'variable',
    'Ceftazidima': 'resistant',
    'Cefepime': 'variable',
    'Ceftarolina': 'sensitive',
    'Ceftobiprole': 'sensitive',
    'Piperacilina-Tazobactam': 'variable',
    'Ticarcilina-Clavulanato': 'variable',
    // Carbapenêmicos
    'Meropenem': 'variable',
    'Imipenem': 'variable',
    'Ertapenem': 'variable',
    'Doripenem': 'variable',
    // Glicopeptídeos
    'Vancomicina': 'sensitive',
    'Teicoplanina': 'sensitive',
    // Lipopeptídeos
    'Daptomicina': 'sensitive',
    // Oxazolidinonas
    'Linezolida': 'sensitive',
    'Tedizolida': 'sensitive',
    // Aminoglicosídeos
    'Gentamicina': 'variable',
    'Tobramicina': 'variable',
    'Amicacina': 'variable',
    'Netilmicina': 'variable',
    'Estreptomicina': 'variable',
    // Quinolonas/Fluoroquinolonas
    'Ciprofloxacino': 'variable',
    'Levofloxacino': 'variable',
    'Moxifloxacino': 'variable',
    'Gatifloxacino': 'variable',
    'Ofloxacino': 'variable',
    // Macrolídeos
    'Eritromicina': 'variable',
    'Claritromicina': 'variable',
    'Azitromicina': 'variable',
    'Roxitromicina': 'variable',
    // Lincosaminas
    'Clindamicina': 'variable',
    // Tetraciclinas
    'Tetraciclina': 'variable',
    'Doxiciclina': 'variable',
    'Minociclina': 'variable',
    'Tigeciclina': 'sensitive',
    // Sulfonamidas
    'SMX-TMP': 'variable',
    'Sulfadiazina': 'variable',
    // Outros
    'Rifampicina': 'variable',
    'Cloranfenicol': 'variable',
    'Fusidato': 'variable',
    'Mupirocina': 'variable',
    'Fosfomicina': 'variable',
    'Nitrofurantoína': 'variable'
  },
  'Staphylococcus epidermidis': {
    'Penicilina G': 'resistant',
    'Oxacilina': 'variable',
    'Cefazolina': 'variable',
    'Vancomicina': 'sensitive',
    'Teicoplanina': 'sensitive',
    'Linezolida': 'sensitive',
    'Daptomicina': 'sensitive',
    'Rifampicina': 'variable',
    'Gentamicina': 'variable',
    'Ciprofloxacino': 'variable',
    'SMX-TMP': 'variable',
    'Clindamicina': 'variable',
    'Tigeciclina': 'sensitive',
    'Tedizolida': 'sensitive',
    'Fusidato': 'variable'
  },
  'Staphylococcus haemolyticus': {
    'Penicilina G': 'resistant',
    'Oxacilina': 'resistant',
    'Vancomicina': 'variable',
    'Teicoplanina': 'variable',
    'Linezolida': 'sensitive',
    'Daptomicina': 'sensitive',
    'Tigeciclina': 'sensitive',
    'Rifampicina': 'variable'
  },
  'Streptococcus pneumoniae': {
    'Penicilina G': 'variable',
    'Ampicilina': 'sensitive',
    'Amoxicilina': 'sensitive',
    'Amoxicilina-Clavulanato': 'sensitive',
    'Cefuroxima': 'variable',
    'Ceftriaxone': 'sensitive',
    'Cefotaxima': 'sensitive',
    'Cefepime': 'variable',
    'Meropenem': 'sensitive',
    'Vancomicina': 'sensitive',
    'Linezolida': 'sensitive',
    'Levofloxacino': 'variable',
    'Moxifloxacino': 'variable',
    'Azitromicina': 'variable',
    'Claritromicina': 'variable',
    'Eritromicina': 'variable',
    'Clindamicina': 'variable',
    'SMX-TMP': 'variable',
    'Tetraciclina': 'variable',
    'Doxiciclina': 'variable',
    'Cloranfenicol': 'variable',
    'Rifampicina': 'sensitive',
    'Daptomicina': 'sensitive',
    'Ceftarolina': 'sensitive'
  },
  'Enterococcus faecalis': {
    'Penicilina G': 'resistant',
    'Ampicilina': 'sensitive',
    'Piperacilina': 'sensitive',
    'Vancomicina': 'variable',
    'Teicoplanina': 'variable',
    'Linezolida': 'sensitive',
    'Daptomicina': 'sensitive',
    'Gentamicina': 'resistant',
    'Estreptomicina': 'variable',
    'Ciprofloxacino': 'resistant',
    'Nitrofurantoína': 'sensitive',
    'Tetraciclina': 'variable',
    'Tigeciclina': 'variable'
  },
  'Enterococcus faecium': {
    'Ampicilina': 'resistant',
    'Penicilina G': 'resistant',
    'Vancomicina': 'variable',
    'Teicoplanina': 'variable',
    'Linezolida': 'sensitive',
    'Daptomicina': 'sensitive',
    'Tigeciclina': 'variable',
    'Quinupristina-Dalfopristina': 'sensitive'
  },
  
  // BGN Enterobactérias
  'Escherichia coli': {
    // Beta-lactâmicos
    'Penicilina G': 'resistant',
    'Ampicilina': 'variable',
    'Amoxicilina': 'variable',
    'Amoxicilina-Clavulanato': 'variable',
    'Ampicilina-Sulbactam': 'variable',
    'Piperacilina': 'variable',
    'Piperacilina-Tazobactam': 'variable',
    'Ticarcilina-Clavulanato': 'variable',
    'Cefazolina': 'variable',
    'Cefalexina': 'variable',
    'Cefuroxima': 'variable',
    'Cefoxitina': 'variable',
    'Ceftriaxone': 'variable',
    'Cefotaxima': 'variable',
    'Ceftazidima': 'variable',
    'Cefepime': 'variable',
    'Ceftolozano-Tazobactam': 'variable',
    'Ceftazidima-Avibactam': 'variable',
    // Carbapenêmicos
    'Meropenem': 'sensitive',
    'Imipenem': 'sensitive',
    'Ertapenem': 'sensitive',
    'Doripenem': 'sensitive',
    'Meropenem-Vaborbactam': 'sensitive',
    'Imipenem-Relebactam': 'sensitive',
    // Aminoglicosídeos
    'Amicacina': 'variable',
    'Gentamicina': 'variable',
    'Tobramicina': 'variable',
    'Netilmicina': 'variable',
    'Plazomicina': 'variable',
    // Quinolonas
    'Ciprofloxacino': 'variable',
    'Levofloxacino': 'variable',
    'Norfloxacino': 'variable',
    'Ofloxacino': 'variable',
    // Outros
    'SMX-TMP': 'variable',
    'Nitrofurantoína': 'sensitive',
    'Fosfomicina': 'sensitive',
    'Tigeciclina': 'sensitive',
    'Polimixina B': 'sensitive',
    'Colistina': 'sensitive',
    'Tetraciclina': 'variable',
    'Doxiciclina': 'variable',
    'Cloranfenicol': 'variable',
    'Aztreonam': 'variable'
  },
  'Klebsiella pneumoniae': {
    'Ampicilina': 'resistant',
    'Amoxicilina-Clavulanato': 'variable',
    'Piperacilina-Tazobactam': 'variable',
    'Cefazolina': 'variable',
    'Cefuroxima': 'variable',
    'Ceftriaxone': 'variable',
    'Cefotaxima': 'variable',
    'Ceftazidima': 'variable',
    'Cefepime': 'variable',
    'Ceftolozano-Tazobactam': 'variable',
    'Ceftazidima-Avibactam': 'variable',
    'Meropenem': 'variable',
    'Imipenem': 'variable',
    'Ertapenem': 'variable',
    'Meropenem-Vaborbactam': 'variable',
    'Amicacina': 'variable',
    'Gentamicina': 'variable',
    'Plazomicina': 'variable',
    'Ciprofloxacino': 'variable',
    'Levofloxacino': 'variable',
    'SMX-TMP': 'variable',
    'Tigeciclina': 'sensitive',
    'Polimixina B': 'sensitive',
    'Colistina': 'sensitive',
    'Fosfomicina': 'variable'
  },
  'Pseudomonas aeruginosa': {
    'Ceftazidima': 'variable',
    'Cefepime': 'variable',
    'Ceftolozano-Tazobactam': 'variable',
    'Ceftazidima-Avibactam': 'variable',
    'Piperacilina-Tazobactam': 'variable',
    'Meropenem': 'variable',
    'Imipenem': 'variable',
    'Doripenem': 'variable',
    'Amicacina': 'variable',
    'Gentamicina': 'variable',
    'Tobramicina': 'variable',
    'Plazomicina': 'variable',
    'Ciprofloxacino': 'variable',
    'Levofloxacino': 'variable',
    'Colistina': 'sensitive',
    'Polimixina B': 'sensitive',
    'Aztreonam': 'variable',
    'Fosfomicina': 'variable'
  },
  'Acinetobacter baumannii': {
    'Ampicilina-Sulbactam': 'variable',
    'Ceftazidima': 'variable',
    'Cefepime': 'variable',
    'Piperacilina-Tazobactam': 'variable',
    'Meropenem': 'variable',
    'Imipenem': 'variable',
    'Amicacina': 'variable',
    'Gentamicina': 'variable',
    'Tobramicina': 'variable',
    'Ciprofloxacino': 'variable',
    'Levofloxacino': 'variable',
    'Colistina': 'sensitive',
    'Polimixina B': 'sensitive',
    'Doxiciclina': 'variable',
    'Tigeciclina': 'variable',
    'Minociclina': 'variable'
  }
};
