
-- Inserção de materiais adicionais conforme quinta tabela enviada na imagem
-- Telas, tubos, válvulas e outros materiais médicos
-- Removido código 4517 que já existe no banco

INSERT INTO public.materials (mv_code, name, observation) VALUES
('3543', 'TELA INORGANICA EM POLIPROPILENO APROX. 15 X 15 CM', 'Unidade: UNIDADE'),
('17576', 'TELA INORGANICA EM POLIPROPILENO APROX. 30 X 30 CM', 'Unidade: UNIDADE'),
('30355', 'TESTE ROWE DICK PACOTE PRONTO MINI C/ 50 UND', 'Unidade: PACOTE'),
('56411', 'TESTE DE CAVITAÇÃO E LAVADORAS ULTRASSÔNICAS', 'Unidade: UNIDADE'),
('33516', 'TESTE RÁPIDO HIV 1 E II QUALIT IMUNOCRÓMATOS TES CONF 10 TES', 'Unidade: CAIXA'),
('467', 'TIRA TESTE P/ DETERMINAÇÃO GLICOSE NO SANGUE', 'Unidade: UNIDADE'),
('402', 'TOUCA CIRÚRGICA DESC TNT 100 BRANCO G P/ ELÁSTICO', 'Unidade: UNIDADE'),
('37561', 'TUBO DE SILICONE 6 X 10MM N. 203 P/ OXIGÊNIO', 'Unidade: METRO'),
('37563', 'TUBO HOSPITALAR EM SILICONE N° 204 6 X 12 MM P/ O2 C/ 15M', 'Unidade: METRO'),
('51315', 'TUBO LATEX N° 206 C/ GARROTE C/ 15 MT', 'Unidade: METRO'),
('91833', 'UMIDIFICADOR TRAQUEALZÃO X NÍVEL TRUST', 'Unidade: UNIDADE'),
('45532', 'UMIDIFICADOR OXIGÊNIO 250ML', 'Unidade: UNIDADE'),
('15533', 'UMIDIFICADOR P/ AR COMPRIMIDO 250ML', 'Unidade: UNIDADE'),
('15376', 'VÁLVULA REGULADORA DE ÓXIDO NITROSO', 'Unidade: UNIDADE'),
('15375', 'VÁLVULA REGULADORA DE OXIGÊNIO P/ REDE', 'Unidade: UNIDADE'),
('53522', 'VÁLVULA REGULADORA DE PRESSÃO P/ REDE DE CO2', 'Unidade: UNIDADE'),
('50153', 'VÁLVULA REGULADORA FLUXÔMETRO GERADOR DE OZÔNIO 1,02 A 4 LPM', 'Unidade: UNIDADE'),
('112113', 'VÁLVULA REGULADORA OXIGÊNIO P/ REDE BRANCO G E', 'Unidade: UNIDADE');
