
-- Inserir mais materiais médicos da nova lista fornecida
INSERT INTO public.materials (mv_code, name, observation) VALUES

-- Drenos torácicos adicionais
('4513', 'DRENO TORÁCICO ESTÉRIL RADIOPACO 26FR - 50CM', 'Unidade: UNIDADE'),
('4514', 'DRENO TORÁCICO ESTÉRIL RADIOPACO 28FR - 50CM', 'Unidade: UNIDADE'),
('4516', 'DRENO TORÁCICO ESTÉRIL RADIOPACO 32FR - 50CM', 'Unidade: UNIDADE'),
('4517', 'DRENO TORÁCICO ESTÉRIL RADIOPACO 34FR - 50CM', 'Unidade: UNIDADE'),
('4518', 'DRENO TORÁCICO ESTÉRIL RADIOPACO 36FR - 50CM', 'Unidade: UNIDADE'),

-- Eletrodos
('47069', 'ELETRODO DESC P/ ECG ESPUMA C/50 UN GEL', 'Unidade: UNIDADE'),
('42664', 'ELETRODO DESCARTÁVEL NEONATAL', 'Unidade: UNIDADE'),

-- Equipamentos diversos
('26079', 'EQUIPO GRAVIT P/ SANGUE E HEMODERIRRADOS - FILTRO 200 MICRAS', 'Unidade: UNIDADE'),
('58025', 'EQUIPO MED. BOMBA INF SANTRONIC - ICASET - E 0424-0200', 'Unidade: UNIDADE'),
('49637', 'EQUIPO MED. FOTO BOMBA INF SANTRONIC - ICASET - E 0422000', 'Unidade: UNIDADE'),
('53959', 'EQUIPO MICRO O BURETA 15ML', 'Unidade: UNIDADE'),
('54445', 'EQUIPO NUTRI ENT BOMBA INF SANTRONIC - ICASET - E 0624C700', 'Unidade: UNIDADE'),
('26373', 'EQUIPO P/ SOL ENTERAL C/ L MACRO GRAVITACIONAL', 'Unidade: UNIDADE'),
('18656', 'EQUIPO P/ SOL PARENT MACROGOTAS GRAVIT C/ INJ LAT E DISP SER', 'Unidade: UNIDADE'),

-- Escovas
('77159', 'ESCOVA ANTISÉPTICA HÁPICA DE TUBO EFOA 37 X 5 X 3 CM', 'Unidade: UNIDADE'),
('61135', 'ESCOVA DENTAL CERDAS PEQUENA INFANTIL MACIA', 'Unidade: UNIDADE'),
('35870', 'ESCOVA P/ DEGERMAÇÃO DAS MÃOS C/ CLOREXIDINA 2%', 'Unidade: UNIDADE'),
('61056', 'ESCOVA P/ LIMPEZA DE ENDOSCÓPIO ORAL - CERDA 1,50M X 3CM', 'Unidade: UNIDADE'),
('21475', 'ESCOVA PLANA CERDAS FLEXÍVEIS 25CM AUTOCLAVÁVEL', 'Unidade: UNIDADE'),

-- Espaçadores
('28519', 'ESPAÇADOR P/ MEDICAÇÃO EM AEROSSOL - SONHINHA', 'Unidade: UNIDADE'),
('12858', 'ESPARADRAPO 100% ALGODÃO 10CM X 4,5M', 'Unidade: ROLO'),
('13957', 'ESPARADRAPO MICROPOROSO DERM BEGE 2,5CM X 10M', 'Unidade: ROLO'),

-- Espéculos
('74517', 'ESPÉCULO VAGINAL DESCARTÁVEL NÃO ESTÉRIL TAM. G', 'Unidade: UNIDADE'),
('74518', 'ESPÉCULO VAGINAL DESCARTÁVEL NÃO ESTÉRIL TAM. M', 'Unidade: UNIDADE'),
('81298', 'ESPÉCULO VAGINAL DESCARTÁVEL NÃO ESTÉRIL TAM. P', 'Unidade: UNIDADE'),
('5547', 'ESPÉCULO NEMSAPAR ESTÉRIL DE GELATINA NUMA 82M12CM 10MM', 'Unidade: UNIDADE'),

-- Estetoscópios
('84750', 'ESTETOSCÓPIO ADULTO', 'Unidade: UNIDADE'),
('85522', 'ESTETOSCÓPIO DIAFRAGMA DUPL FACE DIAM. 2,7 X 1,9 CM NEONATAL', 'Unidade: UNIDADE'),
('84751', 'ESTETOSCÓPIO INFANTIL', 'Unidade: UNIDADE'),

-- Etiquetas e extensores
('89871', 'ETIQUETA ADES DUPLA CAMADA 95X50MM P/ IMPRESS C/ NO QUIM I', 'Unidade: UNIDADE'),
('61403', 'EXTENSOR P/ PROTOCOLO 85FR 1.LAT 25', 'Unidade: UNIDADE'),
('61871', 'EXTENSOR DE PERFUSÃO REVERSÍVEL LUER LOCK 3FR 120CM', 'Unidade: UNIDADE'),
('22759', 'EXTENSOR P/ CATETER LUER ROTATIVO 10FR X 150CM', 'Unidade: UNIDADE'),

-- Faixas
('38348', 'FAIXA DE SMARCH ESTÉRIL 150M X 2M', 'Unidade: UNIDADE'),
('38347', 'FAIXA DE SMARCH ESTÉRIL 300M X 2M', 'Unidade: UNIDADE'),

-- Filtros
('25504', 'FILTRO AZ PARA INCUBADORA DE TRANSPORTE FANEM TI 150 T5', 'Unidade: UNIDADE'),
('34607', 'FILTRO DEAN BACTERIANO VIRAL ADULTO CYTUBO TRAQUEIA', 'Unidade: UNIDADE'),
('32711', 'FILTRO HEPA PARA VENTILADOR MECÂNICO', 'Unidade: UNIDADE'),
('34177', 'FILTRO UMIDIFICADOR DE BARREIRA HMFAEMEF ADULTO C/ TUBO EXT.', 'Unidade: UNIDADE'),
('34176', 'FILTRO UMIDIFICADOR DE BARREIRA HMFAEMEF PEDIÁTRICO', 'Unidade: UNIDADE'),
('34174', 'FILTRO UMIDIFICADOR DE BARREIRA HMEF NEONATO', 'Unidade: UNIDADE'),
('59748', 'FIO AÇO SIN MULT MONOFILAMENT 1,1A 3,5CM CIL 1,5 75CM', 'Unidade: UNIDADE'),
('73721', 'FIO AÇO SIN MULT COLOPLATINA 1 AG 3,7CM CIL 1/2 75CM', 'Unidade: UNIDADE');
