// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbhbsvdomphbdfdzykep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiaGJzdmRvbXBoYmRmZHp5a2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODIzODEsImV4cCI6MjA2NDA1ODM4MX0.5iz1qRuKwk5xeDayI8I5i1biVMXkbBGvN2dgwM4qU-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);